package bookeeping.rest.request.expect;

public enum CommitProperty
{
	commitId, CHANGE_METADATA, NODE_VERSION, NODE_DELETE, FILESYSTEM_CREATE, FILESYSTEM_RESTORE, DIRECTORY_CREATE, DIRECTORY_RESTORE, DIRECTORY_MOVE, FILE_CREATE, FILE_RESTORE, FILE_MOVE, FILE_SHARE, FILE_UNSHARE
}
